version: '3.8'

services:
  backend:
    build: .
    container_name: cyphr-backend
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    env_file:
      - .env.production.server
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - cyphr-network
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: cyphr-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - cyphr-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: cyphr-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - cyphr-network
    depends_on:
      - backend

volumes:
  redis-data:

networks:
  cyphr-network:
    driver: bridge