name: CyphrNative
options:
  bundleIdPrefix: com.cyphrmessenger
  deploymentTarget:
    iOS: 15.0
  createIntermediateGroups: true
  
settings:
  base:
    PRODUCT_NAME: Cyphr
    PRODUCT_BUNDLE_IDENTIFIER: com.cyphrmessenger.ios
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_BITCODE: NO
    LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
  
targets:
  CyphrNative:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: .
        includes:
          - "*.swift"
        excludes:
          - "Package.swift"
          - "main.swift"
          - "TestKyber.swift"
          - "SimpleApp.swift"
      - path: Assets.xcassets
      - path: LaunchScreen.storyboard
      - path: Resources
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.cyphrmessenger.ios
        PRODUCT_NAME: Cyphr
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    dependencies:
      - package: SwiftKyber
        product: SwiftKyber
      - package: SocketIO
        product: SocketIO
      # Stellar SDK будет добавлен позже для wallet функционала

packages:
  SwiftKyber:
    url: https://github.com/leif-ibsen/SwiftKyber
    from: 1.0.0
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    from: 16.1.0